<?php

namespace App\Traits;
trait StallionDeliveryCities
{
    public $stallionDeliveryCities= '<option value="1">Karachi</option>
	<option value="2">Islamabad</option>
	<option value="3">Lahore</option>
	<option value="4">Quetta</option>
	<option value="5">Peshawar</option>
	<option value="6">Rawalpindi</option>
	<option value="7">Multan</option>
	<option value="8">Sukkur</option>
	<option value="9">Faisalabad</option>
	<option value="12">Gujranwala</option>
	<option value="13">Sargodha</option>
	<option value="14">Sialkot</option>
	<option value="15">Hyderabad</option>
	<option value="16">Gujrat</option>
	<option value="17">Jaranwala</option>
	<option value="18">Rahim Yar Khan</option>
	<option value="22">Wah Cantt</option>
	<option value="24">Kharian</option>
	<option value="26">Sadiqabad</option>
	<option value="27">Mansehra</option>
	<option value="28">Taxila</option>
	<option value="29">Dera Ismail Khan</option>
	<option value="30">Nawabshah</option>
	<option value="33">Sahiwal</option>
	<option value="35">Bahawalnagar</option>
	<option value="36">Larkana</option>
	<option value="37">Moro</option>
	<option value="38">Bahria City</option>
	<option value="39">Tando Jam</option>
	<option value="40">Kotri</option>
	<option value="41">Jamshoro</option>
	<option value="43">Sakrand</option>
	<option value="47">Goth Machi FFC</option>
	<option value="55">Attock</option>
	<option value="57">Bahawalpur</option>
	<option value="59">Bannu</option>
	<option value="61">Bhalwal</option>
	<option value="63">Burewala</option>
	<option value="64">Chakwal</option>
	<option value="68">Chiniot</option>
	<option value="69">Chishtian</option>
	<option value="71">Dadu</option>
	<option value="72">Daska</option>
	<option value="73">Dera Ghazi Khan</option>
	<option value="76">Dhudial</option>
	<option value="78">Dina</option>
	<option value="80">Ghotki</option>
	<option value="82">Gojra</option>
	<option value="87">Haripur</option>
	<option value="97">Kamra</option>
	<option value="98">Kashmore</option>
	<option value="99">Kasur</option>
	<option value="100">Khairpur</option>
	<option value="101">Khanewal</option>
	<option value="102">Khushab</option>
	<option value="104">Kohat</option>
	<option value="107">Layyah</option>
	<option value="108">Lodhran</option>
	<option value="109">Mailsi</option>
	<option value="112">Mardan</option>
	<option value="114">Mianwali</option>
	<option value="121">Muzaffarabad</option>
	<option value="123">Nankana Sahib</option>
	<option value="124">Narowal</option>
	<option value="125">Nowshera</option>
	<option value="126">Okara</option>
	<option value="127">Pakpattan</option>
	<option value="136">Samundri</option>
	<option value="137">Sanghar</option>
	<option value="138">Shahdadkot</option>
	<option value="141">Shakargarh</option>
	<option value="142">Sheikhupura</option>
	<option value="151">Tando M Khan</option>
	<option value="157">Vehari</option>
	<option value="179">Rohri</option>
	<option value="182">Lalamusa</option>
	<option value="184">PHALIA</option>
	<option value="206">Taunsa Sharif</option>
	<option value="215">Arifwala</option>
	<option value="228">Sanghar</option>
	<option value="231">Khanewal</option>
	<option value="233">Rawat</option>
	<option value="235">Kahuta</option>
	<option value="242">Farooqabad</option>
	<option value="248">Dijkot</option>
	<option value="249">Rabwah</option>
	<option value="251">Qasba Gujrat</option>
	<option value="252">Jatoi</option>
	<option value="253">Abdul Hakim</option>
	<option value="258">Sohawa</option>
	<option value="259">Mangla</option>
	<option value="261">Mirpur Khas</option>
	<option value="262">Mirpur Khas</option>
	<option value="267">Ahmedpur East</option>
	<option value="268">Ahmedpur Lamma</option>
	<option value="275">BARNALA</option>
	<option value="279">BHIMBER</option>
	<option value="287">Chak Jhumra</option>
	<option value="288">Chaksawari</option>
	<option value="291">CHARSADDA</option>
	<option value="294">CHOWK AZAM</option>
	<option value="295">DADYAL</option>
	<option value="297">DAHARKI</option>
	<option value="302">DAULAT NAGAR</option>
	<option value="305">DERA MURAD JAMALI</option>
	<option value="307">DHANOT</option>
	<option value="310">DOKRI</option>
	<option value="320">FORT ABBAS</option>
	<option value="324">GAMBAT</option>
	<option value="327">GHAKKAR</option>
	<option value="330">GHOUS PUR</option>
	<option value="334">Goth Machi</option>
	<option value="335">GUDDU</option>
	<option value="340">Haroonabad</option>
	<option value="341">Havelian</option>
	<option value="370">Khairpur Nathan Sh</option>
	<option value="372">Khanqa Shareef</option>
	<option value="379">Kot Addu</option>
	<option value="381">Kot Ghulam M</option>
	<option value="387">Lalian</option>
	<option value="391">Malakwal</option>
	<option value="394">Mandi Bahauddin</option>
	<option value="396">MANGOWAL</option>
	<option value="397">MATLI</option>
	<option value="398">MEHAR</option>
	<option value="399">MEHMOOD KOT</option>
	<option value="400">MEHRABPUR</option>
	<option value="403">MIRPUR MATHELO</option>
	<option value="415">NAUDERO</option>
	<option value="423">OKARA CANTT</option>
	<option value="432">PIND DADAN KHAN</option>
	<option value="437">QABOOLA</option>
	<option value="440">QAZI AHMED</option>
	<option value="442">RAHWALI</option>
	<option value="443">RAJANA</option>
	<option value="445">RANIPUR</option>
	<option value="446">RATO DERO</option>
	<option value="447">RENALA KHURD</option>
	<option value="452">SAMBRIAL</option>
	<option value="454">SARAI ALAMGIR</option>
	<option value="457">SEHWAN</option>
	<option value="462">SHIKARPUR</option>
	<option value="463">SHINKIARI</option>
	<option value="465">SIBI</option>
	<option value="471">TANDLIANWALA</option>
	<option value="472">Tando Allah Yar</option>
	<option value="476">THARO SHAH</option>
	<option value="481">UCH SHAREEF</option>
	<option value="489">YAZMAN</option>
	<option value="500">Jhelum</option>
	<option value="501">Jhang</option>
	<option value="502">Abbottabad</option>
	<option value="503">Dunyapur</option>
	<option value="506">Fatima Fertilizer Co</option>
	<option value="508">Ghakhar Mandi</option>
	<option value="509">gaggoo mandi</option>
	<option value="511">mamu kanjan</option>
	<option value="512">Pir mahal</option>
	<option value="513">SATIANA</option>
	<option value="515">harrapa</option>
	<option value="517">hazro</option>
	<option value="520">Jam Sahib</option>
	<option value="521">Jhuddo</option>
	<option value="524">toba tek singh</option>
	<option value="525">shah kot</option>
	<option value="528">Kameer</option>
	<option value="531">kamoke</option>
	<option value="532">kahror pakka</option>
	<option value="533">Khairpur Tamewali</option>
	<option value="535">Gujar Khan</option>
	<option value="537">kot samaba</option>
	<option value="538">Kotla Arab Ali Khan</option>
	<option value="539">kallar syedan</option>
	<option value="543">Mirpur Azad Kashmir</option>
	<option value="547">MORE Eminabad</option>
	<option value="549">MUBARAKPUR</option>
	<option value="553">Naushehra</option>
	<option value="555">karor lal esan</option>
	<option value="558">Painsera</option>
	<option value="559">pano akil</option>
	<option value="563">Qaimpur</option>
	<option value="565">Shuja abad</option>
	<option value="567">shahpur chakar</option>
	<option value="569">Sharakpur</option>
	<option value="570">Muzaffar garh</option>
	<option value="572">Sillanwali</option>
	<option value="576">Tando Soomro</option>
	<option value="579">Wazirabad</option>
	<option value="580">Jhol</option>
	<option value="582">Zahir pir</option>
	<option value="583">Khewra</option>
	<option value="584">naushahro feroze</option>
	<option value="585">Qila Didar Singh</option>
	<option value="587">khan pur</option>
	<option value="588">Liaquatpur</option>
	<option value="591">Ali pur chatta</option>
	<option value="593">kamaliya</option>
	<option value="594">kandh kot</option>
	<option value="595">khairpur mirs</option>
	<option value="599">Chicha Watni</option>
	<option value="600">Sahiwal Chota</option>
	<option value="601">choa saidan shah</option>
	<option value="602">depalpur</option>
	<option value="603">hasil pur</option>
	<option value="604">Feroze Watwan</option>
	<option value="605">jacobabad</option>
	<option value="606">DERA ALLAH YAR</option>
	<option value="10500">Test City</option>
	<option value="10502">Chanab Nagar (Rubwah)</option>
	<option value="10503">Winder</option>
	<option value="10504">Shikar pur</option>
	<option value="10505">Rani Pur</option>
	<option value="10506">Garhi Yaseen</option>
	<option value="10507">Sehwan Sharif</option>
	<option value="10508">Bhan Saeedabad</option>
	<option value="10509">Tando AllahYar</option>
	<option value="10510">Digri</option>
	<option value="10511">Mirwah</option>
	<option value="10512">Tando Jan Muhammad</option>
	<option value="10513">Umerkot</option>
	<option value="10514">PINDDADANKHAN</option>
	<option value="10515">Sarai Alamgir</option>
	<option value="10516">Mipur Khass</option>
	<option value="10517">Mirpur Khas</option>
	<option value="10518">SHIMLA HILL</option>
	<option value="10519">Attock Khurd</option>
	<option value="10520">Badin</option>
	<option value="10521">GOLARCHI</option>
	<option value="10522">Tando Bago</option>
	<option value="10523">Tando Ghulam Ali</option>
	<option value="10524">Tando Mohd.khan</option>
	<option value="10525">Chistian</option>
	<option value="10526">DHARANWALA</option>
	<option value="10527">Faqir Wali</option>
	<option value="10528">FORTABBAS</option>
	<option value="10529">Banu</option>
	<option value="10530">Lakki Marwat</option>
	<option value="10531">Batkhela</option>
	<option value="10532">CHAKDARA</option>
	<option value="10533">Malakand</option>
	<option value="10534">Bhai Pheru</option>
	<option value="10535">Manga Mandi</option>
	<option value="10536">Changa Manga</option>
	<option value="10537">Bhakkar</option>
	<option value="10538">Bhimber A. K</option>
	<option value="10539">Barnala (A.K)</option>
	<option value="10540">Bunner</option>
	<option value="10541">Gaggo Mandi</option>
	<option value="10542">Kalar Kahar</option>
	<option value="10543">Chitral</option>
	<option value="10544">CHAK SWARI(A.K)</option>
	<option value="10545">ISLAM GARH(A.K)</option>
	<option value="10546">Rajanpur</option>
	<option value="10547">TANK</option>
	<option value="10548">Khurrianwala</option>
	<option value="10549">Sangla Hill</option>
	<option value="10550">Gadoon Amazai</option>
	<option value="10551">Gilgit</option>
	<option value="10552">Astore</option>
	<option value="10553">Bhone</option>
	<option value="10554">Hafizabad</option>
	<option value="10555">Jalalpur Bhattian</option>
	<option value="10556">Rasool Pur Tarr</option>
	<option value="10557">Fatehpur</option>
	<option value="10558">Kangra</option>
	<option value="10559">Tando Adam</option>
	<option value="10560">Bhit Shah</option>
	<option value="10561">HALA</option>
	<option value="10562">Matiyari</option>
	<option value="10563">Shadadpur</option>
	<option value="10564">BHARA KHU</option>
	<option value="10565">Jalal Pur Jattan</option>
	<option value="10566">Hajiwala</option>
	<option value="10567">Karianwala</option>
	<option value="10568">Bangla Gogera</option>
	<option value="10569">Noorpur Thal</option>
	<option value="10570">NOWSHERA DT. KH</option>
	<option value="10571">Jehangira</option>
	<option value="10572">Ahmad Pur Sial</option>
	<option value="10573">Gawadar</option>
	<option value="10574">PASNI</option>
	<option value="10575">Turbat</option>
	<option value="10576">Hub Chowki</option>
	<option value="10577">Hub Chowki</option>
	<option value="10578">UTHAL</option>
	<option value="10579">WINDAR</option>
	<option value="10580">BELA</option>
	<option value="10581">GADANI</option>
	<option value="10582">Kark</option>
	<option value="10583">Mandi Usmanwala</option>
	<option value="10584">Kandiaro</option>
	<option value="10585">THERI MIR WAH</option>
	<option value="10586">JAHANIA</option>
	<option value="10587">Dinga</option>
	<option value="10588">Kohatt</option>
	<option value="10589">HANGU</option>
	<option value="10590">PARACHINAR</option>
	<option value="10591">THALL</option>
	<option value="10592">Kotli (a. K)</option>
	<option value="10593">KHURATTA (A.K)</option>
	<option value="10594">NAKIYAL (A.K)</option>
	<option value="10595">New Afzalpur (AK)</option>
	<option value="10596">PULENDRI (A.K)</option>
	<option value="10597">SEHNSA (A.K.)</option>
	<option value="10598">TATA PANI (A.K)</option>
	<option value="10599">Muridke</option>
	<option value="10600">Ferozwala</option>
	<option value="10601">Kala Shah Kaku</option>
	<option value="10602">Kot Abdul Malik</option>
	<option value="10603">Mianwali</option>
	<option value="10604">Mardan</option>
	<option value="10605">Gujar Khan</option>
	<option value="10606">FATEHPUR (CHAK</option>
	<option value="10607">TRANDA MOHD. PA</option>
	<option value="10608">Balakot</option>
	<option value="10609">Batgram</option>
	<option value="10610">BEESHAM</option>
	<option value="10611">Garhi Habib Ullah</option>
	<option value="10612">Qalandarabad</option>
	<option value="10613">Charsadda</option>
	<option value="10614">Mian Channu</option>
	<option value="10615">Tulamba</option>
	<option value="10616">EASAKHEL</option>
	<option value="10617">Kala Bagh</option>
	<option value="10618">Mingora</option>
	<option value="10619">CHAR BAGH (SWAT)</option>
	<option value="10620">MATTA (SWAT)</option>
	<option value="10621">Chittar Pari</option>
	<option value="10622">Mangla Hamlet (a.k.)</option>
	<option value="10623">Mangla Dam</option>
	<option value="10624">Mangla Dam</option>
	<option value="10625">BACHA BAND</option>
	<option value="10626">KHIPRO</option>
	<option value="10627">Kunri</option>
	<option value="10628">MITHI</option>
	<option value="10629">PITHORO</option>
	<option value="10630">Tharparker</option>
	<option value="10631">Murree</option>
	<option value="10632">Bagh (a.k.)</option>
	<option value="10633">Garhi Dopatta</option>
	<option value="10634">Mehmoodkot</option>
	<option value="10635">Nowshera</option>
	<option value="10636">Qadirpur Rawan</option>
	<option value="10637">Zafarwal</option>
	<option value="10638">Yazmaan</option>
	<option value="10639">Bucheri</option>
	<option value="10640">DAUR</option>
	<option value="10641">KHADRO</option>
	<option value="10642">Qazi Ahmad</option>
	<option value="10643">Risal Pur</option>
	<option value="10644">BASSER PUR</option>
	<option value="10645">Hujra Shah Mukeem</option>
	<option value="10646">RENALAKHURD</option>
	<option value="10647">KALASWALA</option>
	<option value="10648">Pasrur</option>
	<option value="10649">PURAB KLAIR</option>
	<option value="10650">Pattoki</option>
	<option value="10651">Kanganpur</option>
	<option value="10652">Theeng More</option>
	<option value="10653">Khuzdar</option>
	<option value="10654">MASTUNG</option>
	<option value="10655">JIWANI</option>
	<option value="10656">MACH</option>
	<option value="10657">Rabwa</option>
	<option value="10658">Kot Radha Kishan</option>
	<option value="10659">Rawalakot (a.k)</option>
	<option value="10660">Fateh Jang</option>
	<option value="10661">Jand</option>
	<option value="10662">Pindi Gheb</option>
	<option value="10663">Chaklala</option>
	<option value="10664">Tarnol</option>
	<option value="10665">SUI</option>
	<option value="10666">Qaboola Sharif</option>
	<option value="10667">Tandlianwala</option>
	<option value="10668">Phullarwan</option>
	<option value="10669">Pindi Bhattian</option>
	<option value="10670">Khan Ka Sharif</option>
	<option value="10671">Shujabad</option>
	<option value="10672">Jalalpur Pirwal</option>
	<option value="10673">Barkhan</option>
	<option value="10674">Dera Ala Yar</option>
	<option value="10675">HALANI</option>
	<option value="10676">HARNAI</option>
	<option value="10677">KOHLU</option>
	<option value="10678">SIBBI</option>
	<option value="10679">THULL</option>
	<option value="10680">Usta Muhammad</option>
	<option value="10681">SWABI</option>
	<option value="10682">KHOTA</option>
	<option value="10683">TOPI</option>
	<option value="10684">Takht-e-Bhai</option>
	<option value="10685">Talagang</option>
	<option value="10686">Tamirgaraha</option>
	<option value="10687">Dir</option>
	<option value="10688">Thatha</option>
	<option value="10689">Chohar Jamali</option>
	<option value="10690">Gharo</option>
	<option value="10691">MAKLI</option>
	<option value="10692">Mir Pur Sakro</option>
	<option value="10693">Shorkot Cantt</option>
	<option value="10694">Shorkot</option>
	<option value="10695">LUDDAN</option>
	<option value="10696">Tibba Sultan Pur</option>
	<option value="10697">Nooriabad</option>
	<option value="10698">Raiwind</option>
	<option value="10699">Mirpur Bathoro</option>
	<option value="10700">Daulat Pur</option>
	<option value="10701">Chenab Nagar</option>
	<option value="10702">Jampur</option>
	<option value="10703">Sambbrial</option>
	<option value="10704">Gujar-Khan</option>
	<option value="10705">Swat</option>
	<option value="10706">Jauharabad</option>
	<option value="10707">Swabii</option>
	<option value="10708">Charsada</option>
	<option value="10709">Gillgit</option>
	<option value="10710">Rawalakot</option>
	<option value="10711">TandoJam</option>
	<option value="10712">KotGhulamM</option>
	<option value="10713">Ali Pur</option>
	<option value="10714">QABOLA</option>
	<option value="10715">RAHWALII</option>
	<option value="10716">RENALAKHURD</option>
	<option value="10717">UCH SHARIF</option>
	<option value="10718">Chistiann</option>
	<option value="10719">OKARA CANTT</option>
	<option value="10720">RENALA KHURD</option>
	<option value="10721">CHOKI BHAGAT</option>
	<option value="10722">SHAHPUR</option>
	<option value="10723">Stallion</option>
	<option value="10724">Luqman</option>
	<option value="10725">Thehri</option>
	<option value="10726">Aggra</option>
	<option value="10727">Khuhra</option>
	<option value="10728">Hingorja</option>
	<option value="10729">Sehtaeja</option>
	<option value="10730">Sobhodero</option>
	<option value="10731">Kotri Kabeer</option>
	<option value="10732">Behlani</option>
	<option value="10733">Pacca Chang</option>
	<option value="10734">Akri Chondiki</option>
	<option value="10735">Chondiko</option>
	<option value="10736">Thari Mirwah</option>
	<option value="10737">Kot Banglow</option>
	<option value="10738">Kotdigi</option>
	<option value="10739">Kumb</option>
	<option value="10740">Bozdar Wada</option>
	<option value="10741">Mirpur Mathlo Ffc</option>
	<option value="10742">Mari Gas</option>
	<option value="10743">Ubaro</option>
	<option value="10744">Pir Jo Goth</option>
	<option value="10745">Gari Mori</option>
	<option value="10746">Piryalo</option>
	<option value="10747">Jhelum</option>
	<option value="10748">Dina</option>
	<option value="10749">Sarai Alamgir</option>
	<option value="10750">Kharian</option>
	<option value="10751">Mangla</option>
	<option value="10752">Jubilee</option>
	<option value="10753">Jamshoro</option>
	<option value="10754">Kotri</option>
	<option value="10755">Hyderabad</option>
	<option value="10756">kahror pakka</option>
	<option value="10757">YAZMAN</option>
	<option value="10758">Ahmedpur East</option>
	<option value="10759">Lodhran</option>
	<option value="10760">Bahawalpur</option>
	<option value="10761">Multan</option>
	<option value="10762">Faisalabad</option>
	<option value="10763">SHAHPUR</option>
	<option value="10764">CHOKI BHAGAT</option>
	<option value="10765">Sahiwal Chota</option>
	<option value="10766">Sillanwali</option>
	<option value="10767">Bhalwal</option>
	<option value="10768">Sargodha</option>
	<option value="10769">Mangla</option>
	<option value="10770">Kharian</option>
	<option value="10771">Sarai Alamgir</option>
	<option value="10772">Dina</option>
	<option value="10773">Jhelum</option>
	<option value="10774">Sharakpur</option>
	<option value="10775">Farooqabad</option>
	<option value="10776">Sheikhupura</option>
	<option value="10777">Nankana Sahib</option>
	<option value="10778">Peshawar</option>
	<option value="10779">Gujranwala</option>';
}
